upload kao yan template
ECUST-Leap/ecust-leap.github.io pull request #27
Opened 2023-01-28 04:31 UTC by paulzrq

2023-01-28 08:24 UTC, Yuchen-Wang-SH requested changes

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +  - <考研>
这里应该把`<>`去掉，因为不是待填项，而就应该写的是考研这两个字

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +# nickname (2019) : program \@ school
这里为啥有 `\`?

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +
`-`每项之间不用空行

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-   ubmajor：xxx
什么是ubmajor？

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-   Grade： GPA xxx/4.00, Ranking: xx/xx
建议这里把GPA和Ranking当作两个sub的bullet point

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-   xx校内科研 xx暑研
这里的话，一段经历应该是一个`-`，而非是写在同一行上的

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-   一段三中一华ibd，一段mbb
同上一条

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +- xxx
致谢未必需要`-`？

2023-01-28 08:24 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +- 如有问题欢迎联系（if possible）[xxx\@xxx.edu](mailto:xxx@xxx.edu){.email}
这个是不是应该在联系方式的subtitle下，和出国模板保持一致

2023-01-28 19:37 UTC, Yuchen-Wang-SH requested changes

2023-01-28 19:37 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +- 如有问题欢迎联系（if possible）[xxx\@xxx.edu](mailto:xxx@xxx.edu){.email}
这里，是不是要跟出国模板一样有个副标题。以及最后的花括号.email是啥意思

2023-01-28 19:37 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-  Grade： GPA xxx/4.00
我原本想的是：

- Grade
  - GPA: 
  - Ranking:

话说我的出国模板是这样写的吗

2023-01-28 19:38 UTC, Yuchen-Wang-SH commented on templates/考研Template.md
> +-  Grade： GPA xxx/4.00
看了下，的确是这么写的

2023-01-28 23:04 UTC, Yuchen-Wang-SH approved these changes

2023-01-29 03:24 UTC, paulzrq commented
its good to me

2023-01-29 03:24 UTC, merged