Create workTemplate.md
ECUST-Leap/ecust-leap.github.io pull request #36
Opened 2023-01-29 16:20 UTC by Muro967

WorkTemplate is done.

2023-01-29 16:25 UTC, Muro967 commented
我好像不太知道怎么直接把我这个模板写好的动作直接关联到项目看板里的进度，所以把它重新归类到看板里了，不知道这样是对的不。

2023-01-29 18:53 UTC, Yuchen-Wang-SH requested changes
Good job! Minor comments

2023-01-29 18:53 UTC, Yuchen-Wang-SH commented on templates/workTemplate.md
> +  - Job @ Firm
这里和出国模板不太一样：

```
### 最终去向

M.S. in Electrical and Computer Engineering @ Carnegie Mellon University

### 录取结果

#### Offer

  - M.S. in ECE @ CMU
  - M.S. in ECE @ Cornell
    - 奖学金: xxx
  - <其他>

#### Rej

  - M.S. in EE @ Stanford
  - ​M.S. in ML @ CMU
  - <其他>
```

2023-01-29 18:53 UTC, Yuchen-Wang-SH commented on templates/workTemplate.md
> +  xxx
这里我觉得可以写成：

```
#### 群面

xxx

#### 单面

xxx
```

2023-01-29 18:53 UTC, Yuchen-Wang-SH commented on templates/workTemplate.md
> +  - 工作
我在想啊，这里写工作还是求职比较好听一点哈哈

2023-01-29 18:53 UTC, Yuchen-Wang-SH commented on templates/workTemplate.md
> +---
如果网页端上可以做的话，可以把文件名改成`work.md`吗？如果网页上不能弄的话我可以弄一下这个

2023-01-29 18:56 UTC, Yuchen-Wang-SH commented
> 我好像不太知道怎么直接把我这个模板写好的动作直接关联到项目看板里的进度，所以把它重新归类到看板里了，不知道这样是对的不。

1. 把这个PR和project关联起来的办法你做的是对的，就是在侧边栏`Projects`里选定那个project
2. 把PR和issue关联起来的办法：1) 在PR的description里写 `Closes #xx`，就能和xx号issue关联起来。2) 在侧边栏`Development`里选定issue，可以通过输入issue的号码来搜索

2023-01-30 02:10 UTC, Muro967 reviewed
All changes have been revised

2023-01-30 02:22 UTC, Yuchen-Wang-SH approved these changes

2023-01-30 02:23 UTC, merged