Create bao_yan.md
ECUST-Leap/ecust-leap.github.io pull request #45
Opened 2023-01-30 08:47 UTC by Oliver20001031

2023-01-30 19:16 UTC, Yuchen-Wang-SH requested changes
minor comments

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - 前五学期均分:
我不太懂哈 为啥前五学期是个参考指标呀

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - 前五学期排名:
需要前六学期排名吗

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +- xx专业/xx课题组 @ xx大学
这个要不要放到这个二级标题的最上面？

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +### Rejxx
Rejxx？

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +- xx专业/xx课题组（预推免） @ xx大学
所以这里的是拿到的offer，上面那些是申请的是嘛？

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - <其他>
这里中间的空行都可以删掉

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +- <其他>
这里中间的空行也是

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +- 毕业要求与去向
这些要不弄成三级标题？

2023-01-30 19:16 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +## 读研体验
这一部分要不要放在申请心得后面？

2023-01-31 02:40 UTC, Oliver20001031 commented on templates/bao_yan.md
> +  - 前五学期均分:
因为夏令营用的是前五学期成绩，预推免用的是前六个的学期的

2023-01-31 02:43 UTC, Oliver20001031 commented on templates/bao_yan.md
> +  - 前五学期排名:
我觉得可以留一下，要是不记得就不写了

2023-01-31 02:44 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - 前五学期均分:
原来如此 学到了

2023-01-31 05:29 UTC, Yuchen-Wang-SH commented
@Oliver20001031 如果改好了的话，记得要重新request review我才能看得见哈

2023-01-31 08:36 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
这个空行估计也得删

2023-01-31 08:36 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +- xx专业/xx课题组 @ xx大学
我在想咱这个是不是要和其他模板统一，就是放在offer的上面

2023-01-31 08:36 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - 前五学期排名:
我是说前六学期，上面模板里只有前五没有前六排名

2023-02-04 08:50 UTC, Yuchen-Wang-SH commented on templates/bao_yan.md
> +  - 前五学期排名:
前六学期排名 === 保研总排名

2023-02-04 08:51 UTC, Yuchen-Wang-SH approved these changes

2023-02-04 08:51 UTC, merged

2023-02-04 08:55 UTC, Yuchen-Wang-SH commented
Closes #保研